# 1:menu

menu:
  Archives: /archives/index.html
  tags: /tags/index.html
  categories: /categories/index.html
  about: /somepage/about/index.html
  留言: /somepage/talk/index.html
  友链: /somepage/友链/index.html
  项目: /somepage/projects/index.html
  yznazo: /yznazo/index.html

# 2:article settings
#
# Please add the following at the head of the article if you need:
#
# ---
# mathjax: true/false #mathjax
# ---
#

# 3:avatar

avatar:
  url: /img/avatar.jpg

# 4:background
#
# Please edit '\source\css\style.styl'.
#

# 5:comments
# LiveRe comments system
# You can get your uid from https://livere.com/insight/myCode (General web site)
comments:
  enable: true
  livere_uid: MTAyMC80Njg5MS8yMzM5Mg==